### ISSUE TITLE
Archaeologist Create Bond

### ISSUE THREAD

**Issue by adamgall** [sarcophagus-org/sarcophagus-v2-contracts#1]
Allow a new address to create a SARCO bond.

Conversely to V1, an archaeologist is considered "registered" as long as they have a positive bond into the system (and are online / connected to the Arch p2p network).

Simply, the system needs to track how much SARCO is bonded into the system at any given time, and how much of it is "free" (see: `free bond` concept from V1).

**Comment by sethhrbek** [comment]
Issue closed via a few PRs -- relevant code is in: 
https://github.com/sarcophagus-org/sarcophagus-v2-contracts/blame/main/contracts/facets/ArchaeologistFacet.sol
https://github.com/sarcophagus-org/sarcophagus-v2-contracts/blob/main/contracts/libraries/LibBonds.sol
