### ISSUE TITLE
Scope out multiplier work

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-contracts#123]
https://www.notion.so/sarcopahgus/Sarcophagus-Contract-Updates-2-3-23-5942e7e6e72746aab5a7fb5eacadd2bc

Scope out task for multiplier -- list out all implementation details if possible.

The other thing (if time permits), is to think about if there is a scenario where we could add this as an upgrade. Worth researching how upgrades affecting storage should be done.

👇🏾

Multiplier work scope
-----------------------
Admin-level configurable multiplier
Need to do at minimum:
  - Add multiplier to `Sarcophagus`.
  - Add diggingFeeMultiplier to `AppStorage`
  - Add admin only setter for `diggingFeeMultiplier` similar to protocol fee setter
  - Add a corresponding .env variable and initialise this in deployment script to 1
  - Set `s.diggingFeeMultiplier` to the .env varialbe in `AppStorageInit.init`
  - On sarcophagus create, the admin-level digging fees should be multiplied into the multiplier:
    `diggingFeesDue = [calculated diggingFeesDue] * s.diggingFeeMultiplier`
  - Store `s.diggingFeeMultiplier` on the new sarcophagus' `multiplier` field.
  - On sarcophagus rewrap and unwrap, the digging fees should be calculated as:
    `diggingFeesDue = [calculated diggingFeesDue] * sarcophagus.multiplier`
  - Add tests on multiplier behaviour

Does using a multiplier add any real value? We don't think so.

Consider:
```
if: 
 dfps == 100
 interval == 100
 multiplier == 1
then: fee == 100 * 100 * 1 == 10_000

if: 
 dfps == 200
 interval == 100
 multiplier == 1
then: fee == 200 * 100 * 1 == 20_000

if:
 dfps == 100
 interval == 100
 multiplier == 2
then: fee == 100 * 100 * 2 == 20_000

--- 

if:
 dfps == 100
 interval == 900
 multiplier == 2
then: fee == 100 * 900 * 2 == 180_000

if:
 dfps == 200
 interval == 900
 multiplier == 1
then: fee == 100 * 900 * 2 == 180_000
```

Using a non-one multiplier (esp. one that is admin controlled) is effectively forcing archaeologists to be more expensive -- something
they can and should be able to do exclusively on their own. No other obvious value is added.

Future upgradability
---------------------
TBD: consider leaving implementation as is. Meantime need to research what needs to be done now to ensure future upgradability to digging fee calculation as a function of time

**Comment by knoll3** [comment]
I agree. I fail to see the usefulness of adding a multiplier. But I haven't talked to Zac directly so I don't have much insight into the motivation behind adding a multiplier.

**Comment by sethhrbek** [comment]
This looks great, thanks for laying this out. Will take the final assessment and get feedback on whether to proceed with implementation or not.
