### ISSUE TITLE
change existingArch.freeBond to freeBond

### ISSUE THREAD

**Issue by 0xbhagi** [sarcophagus-org/sarcophagus-v2-contracts#144]
[L:181](https://github.com/sarcophagus-org/sarcophagus-v2-contracts/blob/main/contracts/facets/ArchaeologistFacet.sol#L181) 
 change change existingArch.freeBond to freeBond or create a new event that tell what changed

**Comment by 0xbhagi** [comment]
https://github.com/sarcophagus-org/sarcophagus-v2-contracts/blob/main/contracts/facets/ArchaeologistFacet.sol#L181 
 change change existingArch.freeBond to freeBond or create a new event that tell what changed

**Comment by DarksightKellar** [comment]
Hey great catch! Would you mind raising a PR with this update?
