### ISSUE TITLE
Look into failing spec

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-contracts#42]
See if this can be recreated locally, or if this is a flicker.

https://github.com/sarcophagus-org/sarcophagus-v2-contracts/runs/7324164424?check_suite_focus=true

![Image](https://user-images.githubusercontent.com/43755993/178777430-7eb482d4-f6ce-4795-9dfb-410b00283a92.png)

**Comment by DarksightKellar** [comment]
@sethhrbek -- I wasn't able to reproduce the failure, even after putting the test in a loop running a thousand times lol.
But it does look like a sorta difference between using Datetime.now and using the timestamp of the latest block (which is more accurate to the real-world anyway).

I'll update all time-based code to use block's latest timestamp in my upcoming PR of updated specs.
